
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";
import { ToastContainer, Bounce } from "react-toastify";
import Navbar from "@/components/Navbar";
import Providers from "./Provider"; 
import { getAuthSession } from "@/lib/auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Breadit",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: React.ReactNode;
  authModal: React.ReactNode;
}>) {
  const session = await getAuthSession();

  return (
    <html
      lang="en"
      className={cn(
        "bg-white text-slate-900 antialiased light",
        inter.className
      )}
    >
    
      <body className="min-h-screen pt-12 bg-slate-100 antialiased">
     
        <Providers session={session}>
          <div className="container max-w-7xl mx-auto h-full pt-12">
            <Navbar />
            {authModal}
            {children}
          </div>

          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
        </Providers>
      </body>
    </html>
  );
}
